# Guardrails Policy Configuration
# Place this file in your repository as .guardrails/policy.yaml

enforcement_mode: warning  # advisory, warning, or blocking

# Block merge on critical/high severity violations
block_on_critical: true
block_on_high: false

# Enable/disable rule categories
enable_security_checks: true
enable_compliance_checks: true
enable_quality_checks: false

# Allowed licenses (for license compliance checks)
allowed_licenses:
  - MIT
  - Apache-2.0
  - Apache-2.0-only
  - BSD-2-Clause
  - BSD-3-Clause
  - ISC
  - MPL-2.0
  - LGPL-2.1
  - LGPL-3.0

# Custom rule overrides
rules:
  SEC-001:
    enabled: true
    severity: critical
  SEC-002:
    enabled: true
    severity: critical
  # Disable lower priority rules for your team
  PERF-001:
    enabled: false

# Team-specific configurations
team_config:
  require_human_review: false
  notify_on_violations: true
  auto_fix_suggestions: true
